name: Auto-Deploy

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.

    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.4.4
      with:
        version: '14.x'
    - run: npm ci
    - run: npm run build -- --base=/ttt-stats/

    - name: Deploy Website to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./dist
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
